apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: clone-repo
  namespace: pcas-ci
spec:
  workspaces:
    - name: source-ci
  params:
    - name: url
      description: The repository url
      type: string
    - name: revision
      description: Repository branch to be cloned
  
  steps:
    - name: clone
      image: bitnami/git
      workingDir: $(workspaces.source-ci.path)/src
      script: |
        #!/bin/sh
        git clone -b "$(params.revision)" "$(params.url)" .
