apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: sonar-analysis
  namespace: pcas-ci
spec:
  workspaces:
    - name: source-ci

  params:
    - name: SONAR_TOKEN_SECRET_NAME
      default: sonarcloud-token
    - name: SONAR_PROJECT_KEY
    - name: SONAR_ORGANIZATION
    - name: SONAR_HOST_URL
      default: https://sonarcloud.io

  
  steps:
    - name: sonar-cloud
      image: maven:3.9.6-eclipse-temurin-17
      workingDir: $(workspaces.source-ci.path)/src
      env:
       - name: MAVEN_CONFIG
         value: $(workspaces.source-ci.path)/.m2
       - name: SONAR_TOKEN
         valueFrom:
          secretKeyRef:
            name: $(params.SONAR_TOKEN_SECRET_NAME)
            key: sonar-token
      script: |
        #!/bin/sh
        echo "SonarAnalysis tasks Started"
        mvn -Dmaven.repo.local=$(workspaces.source-ci.path)/.m2 sonar:sonar \
          -Dsonar.projectKey=$(params.SONAR_PROJECT_KEY) \
          -Dsonar.organization=$(params.SONAR_ORGANIZATION) \
          -Dsonar.host.url=$(params.SONAR_HOST_URL) \
          -Dsonar.login=$SONAR_TOKEN
        echo "Sonar cloud Analysis Done"
      
