apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-pcas
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "create", "update"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelines", "tasks"]
    verbs: ["get", "list", "create", "delete", "update"]
