apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pcas-cd-role
  namespace: pcas-cd
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [ "" ]  # Core API group for pods
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch" ]