apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: pod-readiness
  namespace: pcas-cd
spec:
  params:
    - name: app-label
      type: string
    - name: namespace
      type: string
  steps:
    - name: wait-for-pods
      image: bitnami/kubectl:latest
      script: |
        #!/bin/sh
        echo "Waiting for pods with label 'app=$(params.app-label)' in namespace $(params.namespace) to become ready"
        
        TIMEOUT=60
        END=$((SECONDS+TIMEOUT))
        
        while [ $SECONDS -lt $END]; do
          NOT_READY=$(kubectl get pods -n $(params.namespace) -l app=$(params.app-label)) --field-selector=status.phase!+Running --no-headers | wc -l
          
          READY_CONTAINERS=$(kubectl get pods -n $(params.namespace) -l app=$(params.app-label) -o jsonpath='{.items[*].status.containerStatuses[*].ready}' | grep -c false || true
        
          if [ "NOT_READY" -eq 0 ] && [ "READY_CONTAINERS" -eq 0 ]; then
            echo "✅ All pods are running and containers are ready."
            exit 0
          fi
         
          echo "⌛ Pods not ready yet... checking again in 5 seconds"
          sleep 5
        done
        echo "❌ Pods failed to become ready within $TIMEOUT seconds."
        kubectl get pods -n $(params.namespace) -l app=$(params.app-label)
        exit 1