apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
  namespace: pcas-cd
spec:
  workspaces:
    - name: source-cd
  steps:
    - name: cleaning-workspace
      image: alpine
      workingDir: $(workspaces.source-cd.path)
      script: |
        #!/bin/sh
        echo "Current Working Directory : $(pwd)"
        echo "clearing all workspace"
        rm -rf $(workspaces.source-cd.path)/src
        echo "current Working Directory : $(pwd)"
        echo "listing All components in Pwd : \n $(ls)"
        echo "Ending Script !"
