apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pcas-pr
  namespace: pcas-ci
spec:
  serviceAccountName: pcas-sa-ci
  pipelineRef:
    name: pcas-pipeline
  params:
    - name: url
      value: "https://github.com/GhatgeRitesh/Product-Catalog-API-Service-CI-CD"
    - name: revision
      value: "main"
    - name: SONAR_PROJECT_KEY
      value: "PCAS_SonarQube"
    - name: SONAR_ORGANIZATION
      value: "ghatgeritesh"
    - name: SONAR_TOKEN_SECRET_NAME
      value: sonarcloud-token
    - name: SONAR_HOST_URL
      value: "https://sonarcloud.io"
    - name: IMAGE
      value: "docker.io/riteshghatge5657/pcas-cicd:0.2"
  workspaces:
    - name: source-ci
      PersistentVolumeClaim:
        claimName: source-ci
