apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pcas-pipeline
  namespace: pcas-ci
spec:
  workspaces:
    - name: source-ci
  params:
    - name: url
    - name: revision
    - name: SONAR_TOKEN_SECRET_NAME
    - name: SONAR_PROJECT_KEY
    - name: SONAR_ORGANIZATION
    - name: SONAR_HOST_URL
    - name: IMAGE

  tasks:
    - name: cleanup
      taskRef:
        name: clean-workspace
      workspaces:
        - name: source-ci
          workspace: source-ci

    - name: clone
      taskRef:
        name: clone-repo
      params:
        - name: url
          value: "$(params.url)"
        - name: revision
          value: "$(params.revision)"
      workspaces:
        - name: source-ci
          workspace: source-ci
      runAfter: ["cleanup"]

    - name: build
      taskRef:
        name: build
      workspaces:
        - name: source-ci
          workspace: source-ci
      runAfter: ["clone"]

    - name: unit-test
      taskRef:
        name: test
      workspaces:
        - name: source-ci
          workspace: source-ci
      runAfter: ["build"]

    - name: sonar-cloud
      taskRef:
        name: sonar-analysis
      workspaces:
        - name: source-ci
          workspace: source-ci
      params:
        - name: SONAR_TOKEN_SECRET_NAME
          value: "$(params.SONAR_TOKEN_SECRET_NAME)"
        - name: SONAR_PROJECT_KEY
          value: "$(params.SONAR_PROJECT_KEY)"
        - name: SONAR_ORGANIZATION
          value: "$(params.SONAR_ORGANIZATION)"
        - name: SONAR_HOST_URL
          value: "$(params.SONAR_HOST_URL)"
      runAfter: ["unit-test"]
    
    - name: docker-build-push
      taskRef:
        name: docker-image
      workspaces:
        - name: source-ci
          workspace: source-ci
      params:
        - name: IMAGE
          value: "$(params.IMAGE)"
      runAfter: ["sonar-cloud"]

