apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ci-trigger-template
  namespace: pcas-ci
spec:
  params:
    - name: url
    - name: revision
    - name: SONAR_TOKEN_SECRET_NAME
    - name: SONAR_PROJECT_KEY
    - name: SONAR_ORGANIZATION
    - name: SONAR_HOST_URL
  resourceTemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: pcas-pr-
        namespace: pcas-ci
      spec:
        pipelineRef:
          name: pcas-pipeline
        params:
          - name: url
            value: "https://github.com/GhatgeRitesh/Product-Catalog-API-Service-CI-CD"
          - name: revision
            value: "main"
          - name: SONAR_PROJECT_KEY
            value: "PCAS_SonarQube"
          - name: SONAR_ORGANIZATION
            value: "ghatgeritesh"
          - name: SONAR_TOKEN_SECRET_NAME
            value: sonarcloud-token
          - name: SONAR_HOST_URL
            value: "https://sonarcloud.io"
        workspaces:
          - name: source-ci
            PersistentVolumeClaim:
              claimName: source-ci
        serviceAccountName: pcas-sa-ci