apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pcas-role-binding
  namespace: pcas-ci
subjects:
  - kind: ServiceAccount
    name: pcas-sa-ci
    namespace: pcas-ci
roleRef:
  kind: Role
  name: pcas-role-ci
  apiGroup: rbac.authorization.k8s.io