apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-role-pcas
subjects:
  - kind: ServiceAccount
    name: pcas-sa-ci
    namespace: pcas-ci
roleRef:
  kind: ClusterRole
  name: role-pcas
  apiGroup: rbac.authorization.k8s.io
